"""Report generator for saving content to files."""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
from uuid import uuid4

from core.database import db
from core.pubmed_client import PubMedArticle


class ReportGenerator:
    """Generate and save reports in various formats."""

    def __init__(self, reports_dir: str = "data/reports"):
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def save_markdown(self, content: str, filename: str, date_str: str = None) -> str:
        """Save content as Markdown file."""
        if date_str is None:
            date_str = datetime.now().strftime("%Y-%m-%d")

        date_dir = self.reports_dir / date_str
        date_dir.mkdir(exist_ok=True)

        file_path = date_dir / f"{filename}.md"
        file_path.write_text(content, encoding="utf-8")

        return str(file_path)

    def save_json(
        self, data: Dict[str, Any], filename: str, date_str: str = None
    ) -> str:
        """Save data as JSON file."""
        if date_str is None:
            date_str = datetime.now().strftime("%Y-%m-%d")

        date_dir = self.reports_dir / date_str
        date_dir.mkdir(exist_ok=True)

        file_path = date_dir / f"{filename}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        return str(file_path)

    def generate_daily_report(
        self, date_str: str, articles_data: List[Dict[str, Any]]
    ) -> Dict[str, str]:
        """Generate a daily report with index."""
        date_dir = self.reports_dir / date_str
        date_dir.mkdir(exist_ok=True)

        # Create index markdown
        index_content = f"""# PubMed 文献推送 - {date_str}

## 今日精选 ({len(articles_data)}篇)

"""

        for i, article_data in enumerate(articles_data, 1):
            article = article_data["article"]
            index_content += f"""### {i}. {article.title}

**期刊**: {article.journal}  
**日期**: {article.pub_date}  
**PMID**: [{article.pmid}]({article.url})

---

"""

        index_content += """## 文件清单

- `xiaohongshu_long.md` - 小红书长文案 (1篇)
- `xiaohongshu_short_1.md` - 小红书短文1
- `xiaohongshu_short_2.md` - 小红书短文2
- `wechat_long.md` - 公众号长文 (1篇)
- `wechat_short_1.md` - 公众号短文1
- `wechat_short_2.md` - 公众号短文2

---
*Generated by PubMed Papers Feed*
"""

        index_path = self.save_markdown(index_content, "README", date_str)

        return {"index": index_path}

    async def create_report(
        self,
        articles_with_content: List[Dict[str, Any]],
        selected_indices: Dict[str, List[int]] = None,
    ) -> Dict[str, Any]:
        """Create a complete report for selected articles."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        report_id = str(uuid4())[:8]

        # Default selection: top 5 articles
        if selected_indices is None:
            selected_indices = {
                "xiaohongshu_long": [0],
                "xiaohongshu_short": [1, 2],
                "wechat_long": [0],
                "wechat_short": [1, 2],
            }

        file_paths = {}
        article_ids = []

        # Generate xiaohongshu long (1 article)
        if selected_indices.get("xiaohongshu_long") and articles_with_content:
            idx = selected_indices["xiaohongshu_long"][0]
            if idx < len(articles_with_content):
                data = articles_with_content[idx]
                article_ids.append(data["article"].pmid)
                content = data["content"]["xiaohongshu_long"]
                path = self.save_markdown(content, "xiaohongshu_long", date_str)
                file_paths["xiaohongshu_long"] = path

        # Generate xiaohongshu short (2 articles)
        for i, idx in enumerate(selected_indices.get("xiaohongshu_short", [])[:2], 1):
            if idx < len(articles_with_content):
                data = articles_with_content[idx]
                if data["article"].pmid not in article_ids:
                    article_ids.append(data["article"].pmid)
                content = data["content"]["xiaohongshu_short"]
                path = self.save_markdown(content, f"xiaohongshu_short_{i}", date_str)
                file_paths[f"xiaohongshu_short_{i}"] = path

        # Generate wechat long (1 article)
        if selected_indices.get("wechat_long") and articles_with_content:
            idx = selected_indices["wechat_long"][0]
            if idx < len(articles_with_content):
                data = articles_with_content[idx]
                if data["article"].pmid not in article_ids:
                    article_ids.append(data["article"].pmid)
                content = data["content"]["wechat_long"]
                path = self.save_markdown(content, "wechat_long", date_str)
                file_paths["wechat_long"] = path

        # Generate wechat short (2 articles)
        for i, idx in enumerate(selected_indices.get("wechat_short", [])[:2], 1):
            if idx < len(articles_with_content):
                data = articles_with_content[idx]
                if data["article"].pmid not in article_ids:
                    article_ids.append(data["article"].pmid)
                content = data["content"]["wechat_short"]
                path = self.save_markdown(content, f"wechat_short_{i}", date_str)
                file_paths[f"wechat_short_{i}"] = path

        # Generate index
        index_result = self.generate_daily_report(date_str, articles_with_content[:5])
        file_paths["index"] = index_result["index"]

        # Save to database
        db.save_report(report_id, date_str, article_ids, file_paths)

        return {
            "report_id": report_id,
            "date": date_str,
            "file_paths": file_paths,
            "article_count": len(set(article_ids)),
        }

    def get_report_files(self, date_str: str = None) -> List[Dict[str, Any]]:
        """Get all report files for a date."""
        if date_str is None:
            date_str = datetime.now().strftime("%Y-%m-%d")

        date_dir = self.reports_dir / date_str
        if not date_dir.exists():
            return []

        files = []
        for file_path in sorted(date_dir.glob("*.md")):
            files.append(
                {
                    "name": file_path.stem,
                    "path": str(file_path),
                    "size": file_path.stat().st_size,
                    "modified": datetime.fromtimestamp(
                        file_path.stat().st_mtime
                    ).isoformat(),
                }
            )

        return files

    def read_report(self, file_path: str) -> str:
        """Read a report file."""
        path = Path(file_path)
        if path.exists():
            return path.read_text(encoding="utf-8")
        return ""

    def get_all_dates(self) -> List[str]:
        """Get all dates with reports."""
        dates = []
        if self.reports_dir.exists():
            for date_dir in sorted(self.reports_dir.iterdir()):
                if date_dir.is_dir():
                    dates.append(date_dir.name)
        return dates[::-1]  # Newest first
